version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - 5000
    ports:
      - 5000:5000
    container_name: singularity-task-server
    networks:
      - singularity-task-network
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${SERVER_PORT}

    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    container_name: singularity-task-client
    networks:
      - singularity-task-network
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    stdin_open: true
    tty: true
    environment:
      REACT_APP_PROXY: ${REACT_APP_PROXY}
    command: npm start

networks:
  singularity-task-network:
    driver: bridge

volumes:
  postgres: {}
